### ISSUE TITLE
能开发一下订阅节点时，自动使用非代理进行订阅吗？

### ISSUE THREAD

**Issue by xmasrain** [bcseputetto/Are-u-ok#12]
能开发一下订阅节点时，自动使用非代理进行订阅吗？

**Comment by xmasrain** [comment]
因为有的节点会失效，经常会导致订阅失败

**Comment by bcseputetto** [comment]
你也不说一下你用的是哪个梯子客户端？passwall？ssr-plus？openclash？
如果你是用的passwall的话，可以善用直连代理列表，你可以把更新订阅的链接的域名填入直连列表。
ssr-plus的话已经提供了是否通过代理更新订阅的选项。
openclash应该也可以利用规则来实现直连订阅链接。
并且你误会了，本项目只是提供编译好的软件包，如果你需要对软件包提出功能上的建议，你需要直接去那个项目里提。
比如passwall，你需要直接去[passwall的项目](https://github.com/xiaorouji/openwrt-passwall)里提，openclash需要直接去[openclash的项目](https://github.com/vernesong/OpenClash)里提

**Comment by xmasrain** [comment]
不好意思，我说的是passwall

**Comment by bcseputetto** [comment]
@xmasrain 你可以用passwall的直连代理列表，如果你希望passwall在订阅功能界面直接加上一个开关来控制订阅链接是否走代理，你需要直接向passwall项目提这个功能需求

**Comment by xmasrain** [comment]
谢谢，我觉得善用直连这个就挺好的！
