### ISSUE TITLE
PassWall_4.77-6_aarch64_a53安装出错，AUK9527的4.76-1安装正常

### ISSUE THREAD

**Issue by KisThFir** [bcseputetto/Are-u-ok#13]
报错信息
97% gzip: corrupted data
 ... Decompression failed.
 100%   ... Extraction failed.
Signal caught, cleaning up

**Comment by bcseputetto** [comment]
如果是硬路由很可能因为空间不足而无法解压，导致无法继续安装，请问你是否是硬路由？

**Comment by KisThFir** [comment]
> 如果是硬路由很可能因为空间不足而无法解压，导致无法继续安装，请问你是否是硬路由？

我重置了，空间87MB，我还下载了两次对比md5，你这个包只比AUK9527的大5MB啊，如果真的不够也没办法了🐥

**Comment by bcseputetto** [comment]
@KisThFir AUK9527仓库的旧版本也是我打包的，如果实在空间不够，你还可以尝试在路由器以外的地方解包 .run 包，然后使用里面的 ipk文件，上传安装。
可以在任何Unix平台解包，比如macOS，Linux发行版，Windows的WSL
执行
```console
sh 包名 --noexec --target ./passwall
```
比如
```console
sh PassWall_4.77-6_aarch64_a53_all_sdk_22.03.6.run --noexec --target ./passwall

**Comment by KisThFir** [comment]
@bcseputetto 好的谢谢大佬，我先用着旧版吧，以后需要再按照你说的操作

**Comment by bcseputetto** [comment]
后面可能会考虑给硬路由打包一些小的包。但如果小削减体积，那必定有一些依赖可能会剔除
比如 shadowsocks-rust，或者xray和sing-box只留其一
![image](https://github.com/bcseputetto/Are-u-ok/assets/29139573/dd09bcc9-a2c6-44f6-aedf-69812b49f2b0)
毕竟xray或sing-box单体 支持的协议也很全

**Comment by KisThFir** [comment]
@bcseputetto 或者只留xray和sing-box？其他没必要的弱依赖就不一起打包？

**Comment by bcseputetto** [comment]
比如sing-box和xray也可以跑shadowsocks节点，所以不打包shadowsocks-rust，shadowsocks-rust两个包的确很占空间，sing-box也可以跑hy2，所以单独的hy2依赖也可以考虑去掉

**Comment by bcseputetto** [comment]
@KisThFir 如果可以，帮忙测试一下这个包
[PassWall_4.77-6_aarch64_a53_test.run](https://github.com/bcseputetto/Are-u-ok/raw/master/packages/aarch64/PassWall_4.77-6_aarch64_a53_test.run)
体积削减至34.2MB，你也可以重置路由后测试安装

**Comment by KisThFir** [comment]
> @KisThFir 如果可以，帮忙测试一下这个包 [PassWall_4.77-6_aarch64_a53_test.run](https://github.com/bcseputetto/Are-u-ok/raw/master/packages/aarch64/PassWall_4.77-6_aarch64_a53_test.run) 体积削减至34.2MB，你也可以重置路由后测试安装

谢谢大佬，正常安装，安装完剩余20MB。
