### ISSUE TITLE
向版主求救，请求帮忙。

### ISSUE THREAD

**Issue by cqmr** [bcseputetto/Are-u-ok#14]
在openwrt 22.03.6环境下安装PassWall_4.77-6_aarch64_generic_all_sdk_22.03.6.run，进入WEB设置，状态菜单中的防火墙，出现警告已将防火墙规则与 iptables 和 nftables 混合，不知道这种警告对使用有什么影响？如下图：
![22 03](https://github.com/bcseputetto/Are-u-ok/assets/169730908/9e4c922f-6118-4929-b70e-5694b2789a59)
经大神指导，openwrt 22.03.6使用的防火墙规则是nftables ，可能是在编译passwall配置make meuconfig时使用了默认的 iptables，忘记切换到 nftables ，
可以在编译配置make meuconfig时选择切换，也可以修改编译配置文件为：
```
# CONFIG_PACKAGE_luci-app-passwall_Iptables_Transparent_Proxy is not set
CONFIG_PACKAGE_luci-app-passwall_Nftables_Transparent_Proxy=y
``` 
能否请版主帮忙切换一下passwall防火墙规则重新翻译一下，打包对外发布，解决防火墙规则混用问题。谢谢。

**Comment by bcseputetto** [comment]
@cqmr 本项目的软件包主要是给KoolCenter的iStoreOS使用，iStoreOS目前依旧还在使用firewall3(iptables)
等以后iStoreOS升级到23.05及以后分支时切换到firewall4(nftables)时会考虑

**Comment by bcseputetto** [comment]
@cqmr 顺便本项目编译的passwall是两者都支持的，你没有在passwall高级设置里面切换防火墙工具吗？
