### ISSUE TITLE
AdGuardHome登录之后会跳转到登录界面

### ISSUE THREAD

**Issue by exeron21** [bcseputetto/Are-u-ok#15]
iStoreOS
用过好几个浏览器，都有同样的问题
刚安装好系统日志里有这样几句：

Sun Jun 30 13:25:02 2024 daemon.err uhttpd[6124]: grep: /etc/AdGuardHome.yaml: No such file or directory
Sun Jun 30 13:25:15 2024 daemon.err uhttpd[6124]: grep: /etc/AdGuardHome.yaml: No such file or directory
Sun Jun 30 13:26:13 2024 authpriv.info dropbear[15096]: Child connection from 10.8.0.130:3433
Sun Jun 30 13:26:13 2024 authpriv.notice dropbear[15096]: Password auth succeeded for 'root' from 10.8.0.130:3433
Sun Jun 30 13:30:43 2024 daemon.err AdGuardHome[17240]: 2024/06/30 05:30:43 [error] Couldn't get logging settings from the configuration: yaml: unmarshal errors:
Sun Jun 30 13:30:43 2024 daemon.err AdGuardHome[17240]:   line 110: cannot unmarshal !!seq into home.clientsConfig

这个文件实际上是存在的，也没发现110行有什么语法错误（110行是filters 列表）
登录 ip:3000 ，用默认的root/admin登录成功，会立马跳回登录界面，换浏览器还是一样

**Comment by exeron21** [comment]
新下载的4月20号那个111k的  adguardhome.run iStoreOS版本是最新的istoreos-22.03.6-2024062810

**Comment by bcseputetto** [comment]
@exeron21 不用模版自己配置看看，不要使用快速配置

**Comment by bcseputetto** [comment]
当前模板有问题，之后会发布修复模板的版本，目前先不要使用快速配置，自己手动配置

**Comment by bcseputetto** [comment]
@exeron21 已经更新了新的 AGH，可以试试模板，用户名 admin 密码 adminadmin
当然你也可以自己配置

**Comment by exeron21** [comment]
> @exeron21 已经更新了新的 AGH，可以试试模板，用户名 admin 密码 adminadmin 当然你也可以自己配置

好的，我等会试一下，谢谢
