### ISSUE TITLE
请问大佬，更新显示解压失败是什么意思啊

### ISSUE THREAD

**Issue by weiweed** [bcseputetto/Are-u-ok#17]
![WechatIMG84](https://github.com/user-attachments/assets/2c51a962-3b7f-4b18-90cc-70fab07fd22e)

**Comment by bcseputetto** [comment]
你的图片根本没有传上来

**Comment by weiweed** [comment]
> 你的图片根本没有传上来

已更新

**Comment by weiweed** [comment]
![WechatIMG4](https://github.com/user-attachments/assets/df3132e7-22eb-4644-9a01-957a58b81d3e)

**Comment by bcseputetto** [comment]
@weiweed 终端执行
```
df -h
```
截图执行结果

**Comment by weiweed** [comment]
![WeChat0a2848ed2ca3ef9ce99ba3baf7db7b8c](https://github.com/user-attachments/assets/2773bad7-f408-4d38-83e4-766dcaf6923d)

**Comment by bcseputetto** [comment]
你的OpenWrt，网页后台，系统项 下面有没有一个文件传输？
![QQ_1721725347027](https://github.com/user-attachments/assets/5758a39c-ab7d-4176-9c19-3aaff3d24089)
通过这个文件传输，把 .run 包上传到路由器上。然后来到终端执行
```
cd /tmp/upload
sha256sum OpenClash_0.46.014+x86_64_core.run
sh OpenClash_0.46.014+x86_64_core.run --noexec --target ./openclash
ls openclash/
```
执行完这些，执行结果截图

**Comment by bcseputetto** [comment]
终端再执行
```
opkg list-installed |grep tar
opkg list-installed |grep zip
```
截图执行结果

**Comment by weiweed** [comment]
我确实刚更新了一下固件，我试一试的，不行我更新iStoreOS，我刚下载好

**Comment by bcseputetto** [comment]
@weiweed https://github.com/bcseputetto/Are-u-ok/raw/master/packages/x86_64/OpenClash_TEST.bzip2.run
点击链接下载这个包。看下这个包行不行

**Comment by weiweed** [comment]
还是不行，我更新一下固件吧。。。
