### ISSUE TITLE
小内存路由器需要一个只带有Xray内核的SSRPlus

### ISSUE THREAD

**Issue by tangqiu0205** [bcseputetto/Are-u-ok#18]
最近换了一个路由器,更新了最新版的ssrplus,发现内存有点吃不消,占用快200MB了,是否可以编译一个只有Xray内核的ssrplus来降低内存占用. Xray内核应该能覆盖到大部分协议了.

**Comment by bcseputetto** [comment]
@tangqiu0205 
很遗憾不行，passwall可以做到只安装少量跑节点的内核依赖，是因为它的源码作出了修改
![QQ_1722499857911](https://github.com/user-attachments/assets/42eca705-a1af-4746-9633-ae6a4d6a6337)
passwall把大量的依赖变成了可选的依赖，而ssr-plus并没有。
几个比较占用容量的 `hysteria` `shadowsocks-rust` `mosdns` `naiveproxy` `v2ray-plugin` 均为必须的依赖。
![QQ_1722500169654](https://github.com/user-attachments/assets/5b90f040-2fce-49fe-a638-1b684c7b2738)

**Comment by tangqiu0205** [comment]
@bcseputetto 
谢谢解答, 明白了, 如果我现在换成passwall小空间版(不知到内存占用会不会更高😂),原先ssrplus在软件包那块能删除干净吗.
passwall小空间版似乎只有xray内核,如果换成singbox会不会更好呀

**Comment by bcseputetto** [comment]
@tangqiu0205 passwall小空间版削减了依赖，但是并没有除去sing-box，xray-core和sing-box都可以用，你可以在节点订阅设置界面，把跑你的节点的内核修改为sing-box即可。

**Comment by tangqiu0205** [comment]
好的  谢谢
