### ISSUE TITLE
本项目什么时机发布新版本?

### ISSUE THREAD

**Issue by tangqiu0205** [bcseputetto/Are-u-ok#19]
我发现源项目pw和pw2都已发布新版本, 我想问下咱这项目什么时机打包新版?

**Comment by bcseputetto** [comment]
不是今晚就是明天吧，因为最近在玩黑神话，所以没抽出时间来更新

**Comment by tangqiu0205** [comment]
可以，没得问题。

**Comment by bcseputetto** [comment]
passwall 4.78-2 和 passwall2 1.31-1 已经打包更新
