### ISSUE TITLE
大佬，能不能更新ssrp频繁点

### ISSUE THREAD

**Issue by dechaoz** [bcseputetto/Are-u-ok#21]
大佬，能不能更新ssrp频繁点

**Comment by bg4evk** [comment]
SSR-Plus 早就不更新了吧 还怎么频繁

**Comment by dechaoz** [comment]
更新xray核心就好，别的不要求了。passwall不能屏蔽bt下载啊

**Comment by dechaoz** [comment]
> SSR-Plus 早就不更新了吧 还怎么频繁

更新xray核心就好，别的不要求了。passwall不能屏蔽bt下载啊

**Comment by bcseputetto** [comment]
> 更新xray核心就好，别的不要求了。passwall不能屏蔽bt下载啊

@dechaoz 
已经使用 [helloworld](https://github.com/fw876/helloworld) 项目最新的源码编译并打包了
但很遗憾的是，原项目的源码更新已经处于不怎么活跃的状态，很多依赖也没有更新到最新版本。就拿你想要的`xray-core`来举例，目前还在1.8.24。不能贸然的使用其它的源码把这些依赖全都更新到最新，因为可能会因为某些依赖的新版本变化较大，导致ssr-plus不能兼容该依赖的新版本，但这个只是可能性。
至于你说的passwall不能屏蔽BT下载的情况我表示不是很能理解。
首先BT的下载上传流量走的一般都是非常用端口，也就是BT客户端里面设置的用于传入连接的监听端口，拿qbit举例就是
![QQ_1728230800867](https://github.com/user-attachments/assets/bceb3e93-19fd-4336-ace8-a5dcb8579eaa)
这里设置的这个端口，要么是别人通过连你的这个端口来进行下载或者上传，要么是你连别人设置的该端口进行下载或者上传。
这个端口BT默认是6881，当然现在基本是不会用这个默认端口，基本是都是一万以上的。
而passwall是可以仅代理常用端口的，如下图所示
![QQ_1728231001193](https://github.com/user-attachments/assets/c78b16af-5d44-422a-b23a-cb2b7bb8d4fb)
passwall预设的TCP常用的端口为：22,25,53,143,465,587,853,993,995,80,443
passwall预设的TCP仅网页的端口为：80,443
passwall预设的UDP为所有和DNS，DNS即udp 53端口。
只要对方的BT客户端的监听端口不在这里面，那么下载上传的流量就不会走到核心，而是直接绕开核心走直连。
就算你的tracker走了代理也是如此。tracker是否走代理并不会影响你的下载上传流量走代理。
tracker走代理唯一的问题就是，对方BT客户端会认为你的BT客户端的网络IP是节点IP，从而导致无法连上你，但你依然可以连上别人。而你去连别人时用的就不会是节点IP,而是你实际的家庭网络IP，因为根本就没有走到核心，而是绕开核心直连。
所以TCP,UDP转发端口的限制已经从根本上解决你的BT流量是走直连了。剩下的只要你看情况是否需要把tracker的域名加入直连，让其它用户的BT客户端能连上你真实的IP。

**Comment by dechaoz** [comment]
> > 更新xray核心就好，别的不要求了。passwall不能屏蔽bt下载啊
> 
> @dechaoz 已经使用 [helloworld](https://github.com/fw876/helloworld) 项目最新的源码编译并打包了 但很遗憾的是，原项目的源码更新已经处于不怎么活跃的状态，很多依赖也没有更新到最新版本。就拿你想要的`xray-core`来举例，目前还在1.8.24。不能贸然的使用其它的源码把这些依赖全都更新到最新，因为可能会因为某些依赖的新版本变化较大，导致ssr-plus不能兼容该依赖的新版本，但这个只是可能性。 至于你说的passwall不能屏蔽BT下载的情况我表示不是很能理解。 首先BT的下载上传流量走的一般都是非常用端口，也就是BT客户端里面设置的用于传入连接的监听端口，拿qbit举例就是 ![QQ_1728230800867](https://private-user-images.githubusercontent.com/29139573/373961392-bceb3e93-19fd-4336-ace8-a5dcb8579eaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMzE4NzYsIm5iZiI6MTcyODIzMTU3NiwicGF0aCI6Ii8yOTEzOTU3My8zNzM5NjEzOTItYmNlYjNlOTMtMTlmZC00MzM2LWFjZTgtYTVkY2I4NTc5ZWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDE2MTkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYTYzMjExOGZiZDY4NTVjYzk5YjNjMDBjZDhhMmYzZjQ4MWVhNjk1Y2U3N2FmZGVkNmIxZGZmOGM3MTVmYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.F7XEbTKvRWq0k0E7sV1ApsAOkYkhyDKUt2hkaL9i_Ow) 这里设置的这个端口，要么是别人通过连你的这个端口来进行下载或者上传，要么是你连别人设置的该端口进行下载或者上传。 这个端口BT默认是6881，当然现在基本是不会用这个默认端口，基本是都是一万以上的。 而passwall是可以仅代理常用端口的，如下图所示 ![QQ_1728231001193](https://private-user-images.githubusercontent.com/29139573/373961644-c78b16af-5d44-422a-b23a-cb2b7bb8d4fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMzE4NzYsIm5iZiI6MTcyODIzMTU3NiwicGF0aCI6Ii8yOTEzOTU3My8zNzM5NjE2NDQtYzc4YjE2YWYtNWQ0NC00MjJhLWIyM2EtY2IyYjdiYjhkNGZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDE2MTkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMzFhYTlkMzZmMTc2NzYwNzMyNTMyOTU3YTRlM2E2YWNjMjFiZGQ1MWFhMzdhMDU4ZTJlNjAxNTUyMmEwM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sz-Vpli1o8rsS4lk-WxFXLascjoU9hDdLdCgI11d0og) passwall预设的TCP常用的端口为：22,25,53,143,465,587,853,993,995,80,443 passwall预设的TCP仅网页的端口为：80,443 passwall预设的UDP为所有和DNS，DNS即udp 53端口。 只要对方的BT客户端的监听端口不在这里面，那么下载上传的流量就不会走到核心，而是直接绕开核心走直连。 就算你的tracker走了代理也是如此。tracker是否走代理并不会影响你的下载上传流量走代理。 tracker走代理唯一的问题就是，对方BT客户端会认为你的BT客户端的网络IP是节点IP，从而导致无法连上你，但你依然可以连上别人。而你去连别人时用的就不会是节点IP,而是你实际的家庭网络IP，因为根本就没有走到核心，而是绕开核心直连。 所以TCP,UDP转发端口的限制已经从根本上解决你的BT流量是走直连了。剩下的只要你看情况是否需要把tracker的域名加入直连，让其它用户的BT客户端能连上你真实的IP。

万分感谢大佬详细解答，那我自己研究一下，谢谢!
