### ISSUE TITLE
RK3568 架构的EasePi-R1选择什么架构？

### ISSUE THREAD

**Issue by fengbo731** [bcseputetto/Are-u-ok#22]
您好，

准备购买EasePi-R1 Pro版本，istoreOS亲儿子硬件。

请问，架构上查询貌似是A55，下release中应该选择什么架构呢？

**Comment by bcseputetto** [comment]
@fengbo731 在终端执行release页面上方的命令，看下

**Comment by bcseputetto** [comment]
哦，你还没有购买……

**Comment by fengbo731** [comment]
<img width="843" alt="截屏2024-11-10 11 15 42" src="https://github.com/user-attachments/assets/b8ef1e7a-9047-4272-8ad0-059b6dc48dec">
RK3568是瑞芯微公司设计开发和生产的MPU芯片产品。 RK3568芯片是一款定位中高端的通用型SOC，采用22nm制程工艺，集成4核ARM架构A55处理器和Mali G52 2EE图形处理器，支持4K解码和1080P编码。

A55应该下载哪个？

**Comment by fengbo731** [comment]
感谢大佬

https://mp.weixin.qq.com/s/4aQQRC6C2CkLnQzqhWzyeg

产品页面，

买了的话，准备安装passwall，不知道应该下载哪个版本

**Comment by fengbo731** [comment]
现在非常依赖这个更新。太好用了。所以，如果您的release中没有，是否可以增加这块的支持
ARM的架构太多了。

**Comment by bcseputetto** [comment]
https://github.com/istoreos/istoreos/blob/3c20c95d417b9b288db2e34429e5e7856b899ec7/target/linux/rockchip/rk35xx/target.mk?plain=1#L1-L11
rk35xx 就是a53，你也可以买回来到时候在终端里执行release第二行提供的命令

**Comment by TomFoxLee** [comment]
> 其實一般不太確定架構的話，用 aarch64_generic 就行。

R1 的話是
OPENWRT_BOARD="rockchip/rk35xx"
OPENWRT_ARCH="aarch64_cortex-a53"

不過我一直都用 generic 來著，沒啥問題。
