### ISSUE TITLE
【重要提醒】由于KoolCenter软件中心服务器备案问题导致软件包无法安装的临时解决办法

### ISSUE THREAD

**Issue by bcseputetto** [bcseputetto/Are-u-ok#23]
由于KoolCenter部分域名备案丢失，导致本项目软件包在更新软件源时会遇到KoolCenter软件源连接失败后，判断软件源更新失败而终止脚本的问题。在这里提供两个解决办法。
**解决办法二选一即可**
**解决办法二选一即可**
**解决办法二选一即可**

1. 使用网页终端(ttyd)或者ssh连上后执行以下命令修复iStore【推荐】
```
sh -c "$(curl -sSL https://fw.koolcenter.com/iStoreOS/alpha/fix-istore.sh)"
```
该命令会将iStore以及软件源切换到新的域名，切换后在iStore维护更新iStore版本到最新的`0.1.26-3`

2. 打开路由器网页后台，来到【系统】-【软件包】-【配置OPKG】
![1731404743821](https://github.com/user-attachments/assets/ad590c3b-0f38-4cef-acac-2488375712a3)
将第二个框的软件源，最前面加一个`#` 把这个软件源先注释掉，保存。然后再尝试本项目软件包的安装。
安装完后就可以取消注释了，或者你也可以等KoolCenter的域名备案完毕后再取消注释，当然为了你不会忘记取消注释，还是建议你安装完软件包后立即取消注释，否则影响后续iStore应用商店的使用

**Comment by Jenpo** [comment]
刚好今天弄这个，更新IPV6后的所有配置。
快疯了。

**Comment by never615** [comment]
我周三晚上弄着弄着不行了....晕死我了...

**Comment by CBY1314** [comment]
哎，我还以为是固件坏了又换了一个固件。可以用SSH安装

**Comment by clxo1** [comment]
愉快的用了一天。。。第二天就不能用了

**Comment by shanshangshi** [comment]
不知道怎么弄啊。。。

**Comment by lingchenfs1** [comment]
海外Failed to connect to istore.istoreos.com

**Comment by bcseputetto** [comment]
> 海外Failed to connect to istore.istoreos.com

@lingchenfs1 看下访问情况
https://istore.istoreos.com/repo/all/compat/

**Comment by lingchenfs1** [comment]
> > 海外Failed to connect to istore.istoreos.com
> 
> @lingchenfs1 看下访问情况 https://istore.istoreos.com/repo/all/compat/

无法访问此网站
istore.istoreos.com 的响应时间过长。

**Comment by bcseputetto** [comment]
> 无法访问此网站 istore.istoreos.com 的响应时间过长。

如果你要安装 .run包，可以先用方法二，注释掉KoolCenter的源，然后再安装。
——————
下面是关于新域名访问的问题，麻烦你提供一下对`istore.istoreos.com`的解析查询
Windows/macOS 终端执行
```
nslookup istore.istoreos.com
```

**Comment by bcseputetto** [comment]
我发现海外对这个地址的连通性的确有问题。但`istore.linkease.com`与`istore.istoreos.com`的解析结果是一致的。
如果旧域名没有变更过解析记录，意味着旧域名可用的时候，海外连通性就不太行
https://www.itdog.cn/tcping/istore.istoreos.com:443
![1731776332851](https://github.com/user-attachments/assets/b9130862-2ce6-460e-bcc4-ca2347c63722)

**Comment by lingchenfs1** [comment]
> > 无法访问此网站 istore.istoreos.com 的响应时间过长。
> 
> @lingchenfs1 如果你要安装 .run包，可以先用方法二，注释掉KoolCenter的源，然后再安装。
> 
> 下面是关于新域名访问的问题，麻烦你提供一下对`istore.istoreos.com`的解析查询 Windows/macOS 终端执行
> 
> ```
> nslookup istore.istoreos.com
> ```

服务器:  UnKnown
Address:  192.168.3.1

非权威应答:
名称:    istore.linkease.com
Address:  119.188.240.179
Aliases:  istore.istoreos.com

**Comment by bcseputetto** [comment]
@lingchenfs1 如果你要装 .run 暂时先注释掉那条KoolCenter的源，具体海外访问 `istore.istoreos.com` 需要等KoolCenter想办法解决

**Comment by zousy827** [comment]
使用方法一完美解决

**Comment by QuantumLeap-us** [comment]
海外无法访问

**Comment by PauLmaX668** [comment]
墙内也不能访问

**Comment by Todd-Haylink** [comment]
错误
Collected errors:
 * pkg_init_from_file: Malformed package file /tmp/upload.ipk.
opkg install 命令失败，代码 255。
使用第二个#之后报错这个

**Comment by bcseputetto** [comment]
> 错误 Collected errors:
> 
> * pkg_init_from_file: Malformed package file /tmp/upload.ipk.
>   opkg install 命令失败，代码 255。
>   使用第二个#之后报错这个

@Todd-Haylink 我在下载页面写了“如何安装”，为什么你还能传错地方。。。
罚你去仔细看看下载页面的“如何安装”
