### ISSUE TITLE
SSR-Plus_189_x86_64_all_sdk_22.03.7.run开分片无法启动

### ISSUE THREAD

**Issue by pingshu** [bcseputetto/Are-u-ok#25]
开分片后无法运行

**Comment by bcseputetto** [comment]
@pingshu 建议你到 [luci-app-ssr-plus](https://github.com/fw876/helloworld/issues) 的项目进行反馈，编译源码就如我在release页面所写的那样，是2024-12-04编译的。反馈时尽量提供比较详细的信息。
