### ISSUE TITLE
PassWall2是否能增加自动切换节点功能，老版我记得是有这项的。感谢楼下回答，我去尝试一下。

### ISSUE THREAD

**Issue by mhinefox** [bcseputetto/Are-u-ok#4]

**Comment by CharlesLocke** [comment]
最新的PassWall和PassWall2有这个功能的，你打开Socks就行，每一个Socks节点都可以单独设置自动切换规则。添加一个本地节点比如127.0.0.1指向socks节点，然后你把主节点/默认节点设置成这个本地节点。🎇
