### ISSUE TITLE
openclash无法正确按照 geosite 分流

### ISSUE THREAD

**Issue by somehow22** [bcseputetto/Are-u-ok#5]
无论在设置里是否打开"旁路由模式"那个开关，openclash 的内核总是获取不到域名。。我的 clash 配置应该没问题啊，过去在主路由上的 openwrt 运行正常很久了，也启用了 dns 模式以及 sniffing

所以旁路由模式应该怎么正确使用 openclash 呢？

**Comment by bcseputetto** [comment]
@somehow22 本项目提供的openclash .run软件包 完全和 [openclash](https://github.com/vernesong/OpenClash) 官方项目一样，如果有使用上的问题可以到 openclash项目提交issue，或者到社区向有经验的用户请教。通过 .run软件包安装，和你去官方项目下载 .ipk 安装没有任何区别。
![image](https://github.com/bcseputetto/Are-u-ok/assets/29139573/32cf9d73-0cf8-47e8-8831-1c8d6bf2c014)
如上图所示，.run包里面只是包含三个clash内核，一个install.sh安装脚本，一个luci-app-openclash的ipk
而install.sh里的内容就是执行 opkg update 更新软件源，然后安装 luci-app-openclash，然后将三个内核移动到相应的目录。
