### ISSUE TITLE
安装仓库里最新的openclash会删除istoreos的接口

### ISSUE THREAD

**Issue by Karmylr** [bcseputetto/Are-u-ok#7]
如题。除了docker接口全删了。https://github.com/AUK9527/Are-u-ok 的不会

**Comment by bcseputetto** [comment]
@Karmylr 这是新版 openclash造成的问题。详见这个 [issue](https://github.com/vernesong/OpenClash/issues/3649)
AUK9527仓库是因为是旧版的openclash所以没有这个问题。
本仓库的openclash已经是 openclash的master的最新版本0.45.157

**Comment by bcseputetto** [comment]
你完全可以试一下直接装openclash官方仓库的 ipk会不会出现类似情况，请在你的路由器能够正常访问 github的情况下，打开终端执行
```console
wget https://github.com/vernesong/OpenClash/releases/download/v0.45.157-beta/luci-app-openclash_0.45.157-beta_all.ipk
#下载openclash的ipk
opkg update
#更新软件源
opkg install luci-app-openclash_0.45.157-beta_all.ipk
#安装 luci-app-openclash
```
