### ISSUE TITLE
passwall - 4.741版本沒有負載均衡的功能

### ISSUE THREAD

**Issue by mendoza3579** [bcseputetto/Are-u-ok#8]
我在4.733的版本，也是用您的檔案來下載，完美的出現了全部的功能，但昨晚下載4.741後，負載均衡的功能就再也刷不出來了，然後在您的倉庫就再也找不到4.733的版本的run檔了，能否請您把4.733的版本再給我下一次… 非常感謝

**Comment by bcseputetto** [comment]
负载均衡功能是由依赖`haproxy`软件包实现的。4.74-1版本的 .run包里面我有包含haproxy。理论上不会出现这种问题，实际我自己升级就没有遇到。如果负载均衡不见了，请尝试重新安装`haproxy`软件包。
你可以在`OpenWrt`的Web后台的【系统】-【软件包】里面，将已安装的`haproxy`移除后，重新从opkg源里安装，如果源的可用软件包是空的，记得点一下【更新列表】
你也可以在终端里使用下列命令重装`haporyx`
```console
opkg remove haproxy
opkg update
opkg install haproxy
```

**Comment by mendoza3579** [comment]
萬分感謝您🙏🏻

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

於 週四, 2月 22, 2024 時間 11:04, bcseputetto ***@***.***(mailto:於 週四, 2月 22, 2024 時間 11:04, bcseputetto <<a href=)> 寫道：

**Comment by mendoza3579** [comment]
照您的指示，已經可以了，萬分感謝!!!!!
