### ISSUE TITLE
更新软件源列表错误，请检查路由器自身网络连接以及是否有失效的软件源。

### ISSUE THREAD

**Issue by 138161** [bcseputetto/Are-u-ok#9]
更新软件源列表错误，请检查路由器自身网络连接以及是否有失效的软件源。
首页更新了软件源：阿里，之后还是如此

**Comment by bcseputetto** [comment]
麻烦你把日志贴出来，除了网络原因，还有使用失效了的软件源也不行

**Comment by 138161** [comment]
Collected errors:
 * opkg_download: Failed to download https://istore.linkease.com/repo/all/compat/Packages.gz, curl returned 6.
 * opkg_download: Check your network settings and connectivity.

更新软件源列表错误，请检查路由器自身网络连接以及是否有失效的软件源。



Mon Mar 18 08:40:00 2024 cron.err crond[31955]: USER root pid 1961 cmd /usr/sbin/tencentddns >> /var/log/tencentddns.log 2>&1
Mon Mar 18 08:50:00 2024 cron.err crond[31955]: USER root pid 3704 cmd /usr/sbin/tencentddns >> /var/log/tencentddns.log 2>&1
Mon Mar 18 08:53:43 2024 daemon.info dnsmasq-dhcp[1]: DHCPDISCOVER(br-lan) 34:79:16:bd:47:fe
Mon Mar 18 08:53:43 2024 daemon.info dnsmasq-dhcp[1]: DHCPOFFER(br-lan) 192.168.100.197 34:79:16:bd:47:fe
Mon Mar 18 08:53:43 2024 daemon.info dnsmasq-dhcp[1]: DHCPREQUEST(br-lan) 192.168.100.197 34:79:16:bd:47:fe
Mon Mar 18 08:53:43 2024 daemon.info dnsmasq-dhcp[1]: DHCPACK(br-lan) 192.168.100.197 34:79:16:bd:47:fe HUAWEI_M5-e04ab85503372ef
Mon Mar 18 09:00:00 2024 cron.err crond[31955]: USER root pid 5434 cmd /usr/sbin/tencentddns >> /var/log/tencentddns.log 2>&1
Mon Mar 18 09:10:00 2024 cron.err crond[31955]: USER root pid 7159 cmd /usr/sbin/tencentddns >> /var/log/tencentddns.log 2>&1
Mon Mar 18 09:20:00 2024 cron.err crond[31955]: USER root pid 8900 cmd /usr/sbin/tencentddns >> /var/log/tencentddns.log 2>&1
Mon Mar 18 09:30:00 2024 cron.err crond[31955]: USER root pid 10622 cmd /usr/sbin/tencentddns >> /var/log/tencentddns.log 2>&1
Mon Mar 18 09:33:20 2024 user.info : luci: accepted login on / for root from 192.168.100.182
Mon Mar 18 09:40:00 2024 cron.err crond[31955]: USER root pid 23908 cmd /usr/sbin/tencentddns >> /var/log/tencentddns.log 2>&1

**Comment by bcseputetto** [comment]
麻烦你在路由器的终端里执行一下
```
curl https://istore.linkease.com/repo/all/compat/
```
截图看下

**Comment by 138161** [comment]
iStoreOS 22.03.6, 2024030112
 -------------------------------------------------------
root@iStoreOS:~# curl https://istore.linkease.com/repo/all/compat/
curl: (6) Could not resolve host: istore.linkease.com
root@iStoreOS:~#

**Comment by bcseputetto** [comment]
看起来你没有办法解析 istore.linkease.com ，我足够怀疑你的DNS有问题
继续尝试执行
```console
nslookup istore.linkease.com
nslookup istore.linkease.com 223.5.5.5
```
结果发一下

**Comment by 138161** [comment]
iStoreOS 22.03.6, 2024030112
 -------------------------------------------------------
root@iStoreOS:~# curl https://istore.linkease.com/repo/all/compat/
curl: (6) Could not resolve host: istore.linkease.com
root@iStoreOS:~# nslookup istore.linkease.com
Server:         127.0.0.1
Address:        127.0.0.1:53



root@iStoreOS:~# nslookup istore.linkease.com 223.5.5.5
Server:         223.5.5.5
Address:        223.5.5.5:53

Non-authoritative answer:
Name:   istore.linkease.com
Address: 119.188.240.179

Non-authoritative answer:

root@iStoreOS:~#

**Comment by bcseputetto** [comment]
你路由器当前的DNS有问题，第一个命令是使用你路由器当前的DNS
第二个命令是指定上游为 阿里的公共DNS 223.5.5.5 进行查询
第一个命令明显就失败了，没有查询到这个域名的IP记录。
检查你路由器的DNS设置

**Comment by 138161** [comment]
我就没动过DNS，都是istore和pswall自己设定的

**Comment by bcseputetto** [comment]
如果你是旁路由，请自己设定DNS，可以直接设定为公共DNS
223.5.5.5以及119.29.29.29

**Comment by 138161** [comment]
![Uploading 屏幕截图 2024-03-18 094944.png…]()

**Comment by 138161** [comment]
光猫拨号--istore主路由--ap--电脑

**Comment by 138161** [comment]
IPv4 上游
协议: DHCP 客户端
地址: 192.168.71.75/24
网关: 192.168.71.1
DNS 1: 116.228.111.118
DNS 2: 180.168.255.18
到期时间: 13h 12m 45s
已连接: 1d 10h 47m 15s
设备: 以太网适配器: "eth0"

**Comment by bcseputetto** [comment]
你的截图上传失败了，你当前的DNS是什么？首页DNS那块，以及【网络】-【DHCP/DNS】页面，截图发一下

**Comment by 138161** [comment]
协议: DHCPv6 客户端
地址: 240e:38a:1999:3e00:2e0:70ff:fe5b:bccd/64
网关: fe80::133:7cc9:26ef:3cb
DNS 1: fe80::1
已连接: 1d 22h 47m 32s
设备: 以太网适配器: "eth0"

**Comment by 138161** [comment]
截图不会发，传上来看不到

**Comment by bcseputetto** [comment]
终端执行
```console
nslookup www.baidu.com 116.228.111.118
nslookup www.baidu.com 180.168.255.18
nslookup www.baidu.com fe80::1
```

**Comment by 138161** [comment]
root@iStoreOS:~# nslookup www.baidu.com 116.228.111.118
Server:         116.228.111.118
Address:        116.228.111.118:53

Non-authoritative answer:
www.baidu.com   canonical name = www.a.shifen.com
Name:   www.a.shifen.com
Address: 180.101.50.242
Name:   www.a.shifen.com
Address: 180.101.50.188

Non-authoritative answer:
www.baidu.com   canonical name = www.a.shifen.com
Name:   www.a.shifen.com
Address: 240e:e9:6002:15a:0:ff:b05c:1278
Name:   www.a.shifen.com
Address: 240e:e9:6002:15c:0:ff:b015:146f

root@iStoreOS:~#

**Comment by 138161** [comment]
root@iStoreOS:~# nslookup www.baidu.com 180.168.255.18
Server:         180.168.255.18
Address:        180.168.255.18:53

Non-authoritative answer:
www.baidu.com   canonical name = www.a.shifen.com
Name:   www.a.shifen.com
Address: 180.101.50.188
Name:   www.a.shifen.com
Address: 180.101.50.242

Non-authoritative answer:
www.baidu.com   canonical name = www.a.shifen.com
Name:   www.a.shifen.com
Address: 240e:e9:6002:15c:0:ff:b015:146f
Name:   www.a.shifen.com
Address: 240e:e9:6002:15a:0:ff:b05c:1278

root@iStoreOS:~#

**Comment by 138161** [comment]
root@iStoreOS:~# nslookup www.baidu.com fe80::1
nslookup: can't connect to remote host: Invalid argument
root@iStoreOS:~#

**Comment by bcseputetto** [comment]
看起来就是光猫给路由器发的那个IPv6 DNS有问题，系统优先去用那个IPv6 DNS了

**Comment by 138161** [comment]
是不是应该在wan6口设置里更改dns，使用自定义

**Comment by bcseputetto** [comment]
自己设定DNS吧，去网络，DHCP/DNS里面设置DNS转发，直接用阿里公共DNS和腾讯DNSPod的 223.5.5.5和119.29.29.29吧
![image](https://github.com/bcseputetto/Are-u-ok/assets/29139573/0af9fe85-7739-47ff-b31a-a32b11f31786)

**Comment by bcseputetto** [comment]
DNS设定好之后，可以了吗？如果问题解决了就关闭issue了
issue太久没有活跃的话，我这边也会直接关闭

**Comment by 138161** [comment]
设定dns转发后重启istore，解决，谢谢
-rw-r--r--    1 root     root      54329209 Mar 18 10:03 /tmp/is-root/tmp/PassWall2_1.28-1_x86_64_all_sdk_22.03.6.run
6cada93e04470dcdc07a458891b3163b  /tmp/is-root/tmp/PassWall2_1.28-1_x86_64_all_sdk_22.03.6.run
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing passwall2_1.28-1_with_sdk_22.03.6_libopenssl_1.1  100%  
Downloading https://istore.linkease.com/repo/all/compat/Packages.gz
Updated list of available packages in /var/opkg-lists/istore_compat
Downloading https://istore.linkease.com/repo/all/compat/Packages.sig
Signature check passed.
Downloading https://mirrors.ustc.edu.cn/openwrt/releases/22.03.6/targets/x86/64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://mirrors.ustc.edu.cn/openwrt/releases/22.03.6/targets/x86/64/packages/Packages.sig
Signature check passed.
Downloading https://mirrors.ustc.edu.cn/openwrt/releases/22.03.6/packages/x86_64/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://mirrors.ustc.edu.cn/openwrt/releases/22.03.6/packages/x86_64/base/Packages.sig
Signature check passed.
Downloading https://mirrors.ustc.edu.cn/openwrt/releases/22.03.6/packages/x86_64/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://mirrors.ustc.edu.cn/openwrt/releases/22.03.6/packages/x86_64/luci/Packages.sig
Signature check passed.
Downloading https://mirrors.ustc.edu.cn/openwrt/releases/22.03.6/packages/x86_64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://mirrors.ustc.edu.cn/openwrt/releases/22.03.6/packages/x86_64/packages/Packages.sig
Signature check passed.
Downloading https://mirrors.ustc.edu.cn/openwrt/releases/22.03.6/packages/x86_64/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://mirrors.ustc.edu.cn/openwrt/releases/22.03.6/packages/x86_64/routing/Packages.sig
Signature check passed.
Downloading https://mirrors.ustc.edu.cn/openwrt/releases/22.03.6/packages/x86_64/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading https://mirrors.ustc.edu.cn/openwrt/releases/22.03.6/packages/x86_64/telephony/Packages.sig
Signature check passed.
Upgrading brook on root from 20240214-1 to 20240404-1...
Package haproxy (2.4.22-1) installed in root is up to date.
Upgrading hysteria on root from 2.2.4-1 to 2.3.0-1...
Package naiveproxy (121.0.6167.71-1-1) installed in root is up to date.
Package shadowsocks-libev-config (3.3.5-10) installed in root is up to date.
Package shadowsocks-libev-ss-local (3.3.5-10) installed in root is up to date.
Package shadowsocks-libev-ss-redir (3.3.5-10) installed in root is up to date.
Package shadowsocks-libev-ss-server (3.3.5-10) installed in root is up to date.
Upgrading shadowsocks-rust-sslocal on root from 1.18.1-1 to 1.18.2-1...
Upgrading shadowsocks-rust-ssserver on root from 1.18.1-1 to 1.18.2-1...
Upgrading shadowsocksr-libev-ssr-local on root from 2.5.6-9 to 2.5.6-11...
Upgrading shadowsocksr-libev-ssr-redir on root from 2.5.6-9 to 2.5.6-11...
Upgrading shadowsocksr-libev-ssr-server on root from 2.5.6-9 to 2.5.6-11...
Package simple-obfs (0.0.5-1) installed in root is up to date.
Upgrading sing-box on root from 1.8.5-1 to 1.8.8-1...
iptables: Bad rule (does a matching rule exist in that chain?).
sing-box is stopped!
Command failed: Not found
Package tcping (0.3-1) installed in root is up to date.
Package tuic-client (1.0.0-1) installed in root is up to date.
Upgrading v2ray-geoip on root from 202311230040-1 to 202402220038-1...
Upgrading v2ray-geosite on root from 20231122065640-1 to 20240221053250-1...
Upgrading v2ray-plugin on root from 5.13.0-1 to 5.14.1-1...
Upgrading xray-core on root from 1.8.7-1 to 1.8.9-1...
Command failed: Not found
Configuring shadowsocksr-libev-ssr-server.
Configuring sing-box.
sing-box is started!
Configuring hysteria.
Configuring shadowsocks-rust-ssserver.
Configuring v2ray-plugin.
Configuring shadowsocks-rust-sslocal.
Configuring shadowsocksr-libev-ssr-local.
Configuring xray-core.
Configuring v2ray-geoip.
Configuring v2ray-geosite.
Configuring brook.
Configuring shadowsocksr-libev-ssr-redir.
Upgrading luci-app-passwall2 on root from 1.26-1 to 1.28-1...
Upgrading luci-i18n-passwall2-zh-cn on root from git-24.051.30405-9e892fd to git-24.074.36964-dcd9fe5...
Configuring luci-app-passwall2.
Configuring luci-i18n-passwall2-zh-cn.

**Comment by bcseputetto** [comment]
所以搞到最后还是网络上的问题。问题解决了就行。

**Comment by 138161** [comment]
carsh和pswall又出来的，不搞了，还是谢谢你
Downloading https://mirrors.ustc.edu.cn/openwrt/releases/22.03.6/packages/x86_64/telephony/Packages.sig
Signature check passed.
Collected errors:
 * opkg_download: Failed to download https://istore.linkease.com/repo/all/compat/Packages.gz, curl returned 6.
 * opkg_download: Check your network settings and connectivity.

更新软件源列表错误，请检查路由器自身网络连接以及是否有失效的软件源。

**Comment by bcseputetto** [comment]
本项目的包里的安装脚本对 opkg update做了判断，只要更新失败就不会继续安装，所以一定要确保所有软件源都能正常连接
